version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - echo "开始构建..."
      - npm install
      - npm run build
      - echo npm run build completed on 'date'
artifacts:
  files:
    - dist/shop/*
    - dist/shop/assets/
